FROM oracle/glassfish
MAINTAINER Simone Scalabrino<simone.scalabrino@unimol.it>

COPY target/backend-1.0-SNAPSHOT.war glassfish5/glassfish/domains/domain1/autodeploy

EXPOSE 8080:8080
EXPOSE 8181:8181
EXPOSE 4848:4848