# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cobertura:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Cobertura
      run: mvn -B cobertura:cobertura
    - name: Upload report
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: backend/target/site/cobertura
     
  pmd-cpd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run PMD
      run: mvn -B clean package -DskipTests pmd:pmd pmd:cpd
    - name: Upload PMD report
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: backend/target/site/pmd.html
        retention-days: 1
    - name: Upload CPD report
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: backend/target/site/cpd.html